[dependencies]
tower = "0.4.13"
tower-http = {version = "0.5.2", features = ["tracing", "trace"]}
tracing = "0.1.40"
tracing-subscriber = {version = "0.3.18", features = ["json"]}

[package]
edition = "2021"
name = "shared"
version = "0.1.0"
